// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWOkGXOGBKN1sK5Bmfs22oSNJa1QUxM3o',
    appId: '1:178411690068:web:ad69c761196aaaefe975c1',
    messagingSenderId: '178411690068',
    projectId: 'pershoe',
    authDomain: 'pershoe.firebaseapp.com',
    storageBucket: 'pershoe.firebasestorage.app',
    measurementId: 'G-ZGNB8RVVQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl6m4spxs_BvIENzuuBxfOnhVQymFguoo',
    appId: '1:178411690068:android:b781db85de70b271e975c1',
    messagingSenderId: '178411690068',
    projectId: 'pershoe',
    storageBucket: 'pershoe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYhqif32ww4die0w_MqzlvhKoWQVIVmMM',
    appId: '1:178411690068:ios:bb2d4676dc2ab5f3e975c1',
    messagingSenderId: '178411690068',
    projectId: 'pershoe',
    storageBucket: 'pershoe.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYhqif32ww4die0w_MqzlvhKoWQVIVmMM',
    appId: '1:178411690068:ios:bb2d4676dc2ab5f3e975c1',
    messagingSenderId: '178411690068',
    projectId: 'pershoe',
    storageBucket: 'pershoe.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWOkGXOGBKN1sK5Bmfs22oSNJa1QUxM3o',
    appId: '1:178411690068:web:fd53b4646466b6fee975c1',
    messagingSenderId: '178411690068',
    projectId: 'pershoe',
    authDomain: 'pershoe.firebaseapp.com',
    storageBucket: 'pershoe.firebasestorage.app',
    measurementId: 'G-DVQY5DE54B',
  );
}
